[
  ["Almond-leaved pear","Pyrus spinosa"  ],
  ["Altai apple","Malus sieversii"  ],
  ["Amelanchier parviflora","Amelanchier parviflora"  ],
  ["Apple","Malus domestica"  ],
  ["Apricot-leaved pear","Pyrus armeniacifolia"  ],
  ["Asian pear","Pyrus pyrifolia"  ],
  ["Balat","Manilkara bidentata"  ],
  ["Birchleaf pear","Pyrus betulifolia"  ],
  ["Bronze loquat","Eriobotrya deflexa"  ],
  ["Callery pear","Pyrus calleryana"  ],
  ["Calva crabapple","Malus kansuensis"  ],
  ["Canadian serviceberry","Amelanchier canadensis"  ],
  ["Caqui","Manilkara kauki"  ],
  ["Cerrado pear","Eugenia klotzschiana"  ],
  ["Chicle","Manilkara chicle"  ],
  ["Chinese crab apple","Malus hupehensis"  ],
  ["Chinese flowering apple","Malus spectabilis"  ],
  ["Chinese pearleaf crabapple","Malus asiatica"  ],
  ["Chinese quince","Pseudocydonia sinensis"  ],
  ["Chinese serviceberry","Amelanchier sinica"  ],
  ["Chinese white pear","Pyrus — bretschneideri"  ],
  ["Chokeberry","Aronia melanocarpa"  ],
  ["Coastal serviceberry","Amelanchier obovalis"  ],
  ["Cocky apple","Planchonia careya"  ],
  ["Cow tree fruit","Manilkara elata"  ],
  ["Downy serviceberry","Amelanchier arborea"  ],
  ["Dusky pear","Pyrus phaeocarpa"  ],
  ["Eastern crabapple","Malus orientalis"  ],
  ["Eastern mayhaw","Crataegus aestivalis"  ],
  ["European crab apple","Malus sylvestris"  ],
  ["European wild pear","Pyrus pyraster"  ],
  ["Florentine crabapple","Malus florentina"  ],
  ["Greene's mountain-ash fruit","Sorbus scopulina"  ],
  ["Hall crabapple","Malus halliana"  ],
  ["Hawthorn","Crataegus rhipidophylla"  ],
  ["Indian wild pear","Pyrus pashia"  ],
  ["Intermediate serviceberry","Amelanchier intermedia"  ],
  ["Jagua","Genipa americana"  ],
  ["Japanese crab","Malus floribunda"  ],
  ["Juneberry","Amelanchier lamarckii"  ],
  ["Kaido crab apple",""  ],
  ["Kazak pear","Pyrus korshinskyi"  ],
  ["Khirni","Manilkara hexandra"  ],
  ["Korean juneberry","Amelanchier asiatica"  ],
  ["Lebanese wild apple","Malus trilobata"  ],
  ["Loquat","Eriobotrya japonica"  ],
  ["Lovi-lovi","Flacourtia inermis"  ],
  ["Low juneberry","Amelanchier spicata"  ],
  ["Low serviceberry","Amelanchier humilis"  ],
  ["Manchurian crab apple","Malus mandshurica"  ],
  ["Massaranduba","Manilkara bella"  ],
  ["Medlar","Mespilus germanica"  ],
  ["Mountain serviceberry","Amelanchier bartramiana"  ],
  ["Nantucket serviceberry","Amelanchier nantucketensis"  ],
  ["Niedzwetzky's apple","Malus niedzwetzkyana"  ],
  ["NokaidÅ","Malus spontanea"  ],
  ["Oleaster-leafed pear","Pyrus elaeagrifolia"  ],
  ["Pacific crabapple","Malus fusca"  ],
  ["Pale serviceberry","Amelanchier pallida"  ],
  ["Pear","Pyrus communis"  ],
  ["Pillar apple","Malus tschonoskii"  ],
  ["Plumleaf crab apple","Malus prunifolia"  ],
  ["Plymouth pear","Pyrus cordata"  ],
  ["Prairie crabapple","Malus ioensis"  ],
  ["Pratt's crabapple","Malus prattii"  ],
  ["Pyrus glabra","Pyrus glabra"  ],
  ["Quince","Cydonia oblonga"  ],
  ["Ramontchi","Flacourtia indica"  ],
  ["Red-checked crab apple","Malus toringoides"  ],
  ["Regel pear","Pyrus regelii"  ],
  ["Roundleaf serviceberry","Amelanchier sanguinea"  ],
  ["Rowan","Sorbus aucuparia"  ],
  ["Sapodilla","Manilkara zapota"  ],
  ["Sargent crabapple","Malus sargentii"  ],
  ["Saskatoon","Amelanchier alnifolia"  ],
  ["Scarlet firethorn","Pyracantha coccinea"  ],
  ["Shipova"," Pyraria irregularis"  ],
  ["Shrub apple","Malus brevipes"  ],
  ["Siberian crab apple","Malus baccata"  ],
  ["Sikkim crabapple","Malus sikkimensis"  ],
  ["Small-fruited crab apple","Malus transitoria"  ],
  ["Smooth serviceberry","Amelanchier laevis"  ],
  ["Snow pear","Pyrus nivalis"  ],
  ["Snowy mespilus","Amelanchier ovalis"  ],
  ["Sorb","Sorbus domestica"  ],
  ["Southern crabapple","Malus angustifolia"  ],
  ["Sweet crabapple","Malus coronaria"  ],
  ["Syrian pear","Pyrus syriaca"  ],
  ["Taiwan crabapple","Malus doumeri"  ],
  ["Taiwanese rowan","Sorbus randaiensis"  ],
  ["Toringo crabapple","Malus toringo"  ],
  ["Toyon","Heteromeles arbutifolia"  ],
  ["Ussurian pear","Pyrus ussuriensis"  ],
  ["Utah serviceberry","Amelanchier utahensis"  ],
  ["Vilmorin's rowan","Sorbus vilmorinii"  ],
  ["Whitebeam fruit","Sorbus aria"  ],
  ["Wiegand's serviceberry","Amelanchier interior"  ],
  ["Wild dilly","Manilkara jaimiqui"  ],
  ["Wild service tree fruit","Sorbus torminalis"  ],
  ["Wood pear","Pyrus xerophila"  ],
  ["Yunnan crabapple","Malus yunnanensis"  ],
  ["Zumi crabapple","Malus — zumi"  ],
  ["AÃ§aÃ­","Euterpe oleracea"  ],
  ["Acerola","Malpighia emarginata"  ],
  ["Afghan cherry","Prunus jacquemontii"  ],
  ["African mango","Irvingia gabonensis"  ],
  ["African mangosteen","Garcinia livingstonei"  ],
  ["African oil palm fruit","Elaeis guineensis"  ],
  ["Aguasiqui","Prunus gentryi"  ],
  ["Alaskan bunchberry","CornusÂ Ã—Â unalaschkensis"  ],
  ["Allegheny plum","Prunus alleghaniensis"  ],
  ["Almond","Prunus amygdalus"  ],
  ["Amazon grape","Pourouma cecropiifolia"  ],
  ["Ambarella","Spondias dulcis"  ],
  ["American oil palm fruit","Elaeis oleifera"  ],
  ["American plum","Prunus americana"  ],
  ["Apricot","Prunus armeniaca"  ],
  ["Apricot plum","Prunus simonii"  ],
  ["Arabian wild almond","Prunus arabica"  ],
  ["Arnott's mountain black plum","Syzygium densiflorum"  ],
  ["Atoto","Syzygium thompsonii"  ],
  ["Avocado","Persea americana"  ],
  ["Bambangan","Mangifera pajang"  ],
  ["Beach butia","Butia catarinensis"  ],
  ["Beach plum","Prunus maritima"  ],
  ["Bear's plum","Prunus ursina"  ],
  ["Beccari","Butia capitata"  ],
  ["Ber","Ziziphus nummularia"  ],
  ["Bignay","Antidesma bunius"  ],
  ["Binjai","Mangifera caesia"  ],
  ["Bird cherry","Prunus padus"  ],
  ["Black cherry","Prunus serotina"  ],
  ["Black plum","Prunus nigra"  ],
  ["Blue guarri","Euclea crispa"  ],
  ["Blue lilly pilly","Syzygium oleosum"  ],
  ["Bokhara plum","Prunus bokhariensis"  ],
  ["Bolivian mountain coconut","Parajubaea torallyi"  ],
  ["BrianÃ§on apricot","Prunus brigantina"  ],
  ["Broad-leaved lilly pilly fruit","Syzygium hemilamprum"  ],
  ["Broom jelly palm fruit","Butia pubispatha"  ],
  ["Brush cherry","Syzygium australe"  ],
  ["Buffalo-thorn","Ziziphus mucronata"  ],
  ["Burdekin plum","Pleiogynium timoriense"  ],
  ["Bush butter fruit","Dacryodes edulis"  ],
  ["Butia arenicola","Butia arenicola"  ],
  ["Butia campicola","Butia campicola"  ],
  ["Butia matogrossensis","Butia matogrossensis"  ],
  ["CabeÃ§udo","Butia purpurascens"  ],
  ["Calligonum junceum","Calligonum junceum"  ],
  ["Canadian bunchberry","Cornus canadensis"  ],
  ["Casimiroa","Casimiroa edulis"  ],
  ["Cedar Bay cherry","Eugenia reinwardtiana"  ],
  ["Changunga","Byrsonima crassifolia"  ],
  ["Cherry elaeagnus","Elaeagnus multiflora"  ],
  ["Cherry laurel","Prunus laurocerasus"  ],
  ["Cherry of the Rio Grande","Eugenia involucrata"  ],
  ["Cherry plum","Prunus cerasifera"  ],
  ["Chickasaw plum","Prunus angustifolia"  ],
  ["Chinese bush cherry","Prunus glandulosa"  ],
  ["Chinese date","Ziziphus mauritiana"  ],
  ["Chinese plum","Prunus salicina"  ],
  ["Chinese sour cherry","Prunus pseudocerasus"  ],
  ["Choke cherry","Prunus virginiana"  ],
  ["ChupÃ³n","Pouteria amygdalicarpa"  ],
  ["Clove cherry","Prunus apetala"  ],
  ["Coarse dodder-laurel fruit","Cassytha melantha"  ],
  ["Coconut","Cocos nucifera"  ],
  ["Cocoplum","Chrysobalanus icaco"  ],
  ["Coffeeberry","Frangula californica"  ],
  ["Cone cherry","Prunus conadenia"  ],
  ["Coolamon","Syzygium moorei"  ],
  ["Cornelian cherry","Cornus mas"  ],
  ["Corozo palm fruit","Bactris guineensis"  ],
  ["Country-almond","Terminalia catappa"  ],
  ["Creek plum","Prunus rivularis"  ],
  ["Crowberry","Empetrum nigrum"  ],
  ["Curry berry","Murraya koenigii"  ],
  ["Cyclamin cherry","Prunus cyclamina"  ],
  ["Damson","Prunus domestica subsp. insititia"  ],
  ["Darvaz plum","Prunus darvasica"  ],
  ["Date","Phoenix dactylifera"  ],
  ["David's peach","Prunus davidiana"  ],
  ["Dawyck cherry","Prunus — dawyckensis"  ],
  ["Desert almond","Prunus fasciculata"  ],
  ["Desert apricot","Prunus fremontii"  ],
  ["Desert peach","Prunus andersonii"  ],
  ["Desert quandong","Santalum acuminatum"  ],
  ["Dhung","Syzygium caryophyllatum"  ],
  ["Dog cherry","Prunus buergeriana"  ],
  ["Dwarf butia","Butia lallemantii"  ],
  ["Dwarf jelly palm fruit","Butia archeri"  ],
  ["Dwarf Russian almond","Prunus tenella"  ],
  ["Dwarf yatay palm fruit","Butia paraguayensis"  ],
  ["Emblic","Phyllanthus emblica"  ],
  ["Emu apple","Owenia acidula"  ],
  ["Engkala","Litsea garciae"  ],
  ["European dwarf cherry","Prunus fruticosa"  ],
  ["European plum","Prunus domestica"  ],
  ["Fenzl's almond","Prunus fenzliana"  ],
  ["Fergana peach","Prunus ferganensis"  ],
  ["Fibrous satinash fruit","Syzygium fibrosum"  ],
  ["Flatwoods plum","Prunus umbellata"  ],
  ["Flowering almond","Prunus triloba"  ],
  ["Fuji cherry","Prunus incisa"  ],
  ["Gandaria","Bouea macrophylla"  ],
  ["Gansu peach","Prunus kansuensis"  ],
  ["Gomortega","Gomortega keule"  ],
  ["Gowok","Syzygium polycephalum"  ],
  ["Gray-leaf cherry","Prunus canescens"  ],
  ["Greengage","Prunus domestica subsp. italica"  ],
  ["Green plum","Buchanania obovata"  ],
  ["Grey satinash fruit","Syzygium claviflorum"  ],
  ["Guavaberry","Myrciaria floribunda"  ],
  ["Guarana","Paullinia cupana"  ],
  ["Gubinge","Terminalia ferdinandiana"  ],
  ["Guinea sour pod","Dialium guineense"  ],
  ["Hackberry","Celtis occidentalis"  ],
  ["Hairless rambutan","Nephelium xerospermoides"  ],
  ["High-eaves syzygium","Syzygium oblatum"  ],
  ["Himalayan bird cherry","Prunus cornuta"  ],
  ["Hokkaido bird cherry","Prunus ssiori"  ],
  ["Hollyleaf cherry","Prunus ilicifolia"  ],
  ["Hortulan plum","Prunus hortulana"  ],
  ["Italian plum","Prunus cocomilia"  ],
  ["Jackal jujube","Ziziphus oenopolia"  ],
  ["Jambolan","Syzygium cumini"  ],
  ["Japanese alpine cherry","Prunus nipponica"  ],
  ["Japanese apricot","Prunus mume"  ],
  ["Japanese bird cherry","Prunus grayana"  ],
  ["Japanese bush cherry","Prunus japonica"  ],
  ["Japanese cherry","Prunus serrulata"  ],
  ["Japanese silverberry","Elaeagnus umbellata"  ],
  ["Jelly palm fruit","Butia odortata"  ],
  ["Jocote","Spondias purpurea"  ],
  ["Johnstone River satinash fruit","Syzygium erythrocalyx"  ],
  ["Jujube","Ziziphus jujuba"  ],
  ["Kaong","Arenga pinnata"  ],
  ["Kelsey plum","Prunus salicinaÂ spp."  ],
  ["King coconut","Cocos nuciferaÂ var.Â aurantiaca"  ],
  ["Lipote","Syzygium curranii"  ],
  ["Lipote","Syzygium polycephaloides"  ],
  ["Korlan","Nephelium hypoleucum"  ],
  ["Lala palm","Hyphaene coriacea"  ],
  ["Lemonadeberry","Rhus integrifolia"  ],
  ["Lemon aspen fruit","Acronychia acidula"  ],
  ["Lilly pilly","Syzygium smithii"  ],
  ["Little gooseberry","Buchanania arborescens"  ],
  ["Lockerbie satinash fruit","Syzygium branderhorstii"  ],
  ["Longan","Dimocarpus longan"  ],
  ["Long-flowered syzygium","Syzygium cerasiforme"  ],
  ["Long-peduncled almond","Prunus pedunculata"  ],
  ["Lychee","Litchi chinensis"  ],
  ["Magenta lilly pilly","Syzygium paniculatum"  ],
  ["Malay rose apple","Syzygium malaccense"  ],
  ["Mamey sapote","Pouteria sapota"  ],
  ["Manchurian apricot","Prunus mandshurica"  ],
  ["Manchurian cherry","Prunus maackii"  ],
  ["Mango","Mangifera indica"  ],
  ["Mardarrgu","Ziziphus quadrilocularis"  ],
  ["Marula","Sclerocarya birrea"  ],
  ["Mexican plum","Prunus mexicana"  ],
  ["Millaa millaa","Elaeagnus triflora"  ],
  ["Miracle fruit","Synsepalum dulcificum"  ],
  ["Mistol","Ziziphus mistol"  ],
  ["Miyama cherry","Prunus maximowiczii"  ],
  ["Moriche palm fruit","Mauritia flexuosa"  ],
  ["Muntrie","Kunzea pomifera"  ],
  ["Murray's plum","Prunus murrayana"  ],
  ["Nance","Byrsonima crassifolia"  ],
  ["Nanjing cherry","Prunus tomentosa"  ],
  ["Nannyberry","Viburnum lentago"  ],
  ["Nectarine","Prunus persicaÂ var.Â nucipersica"  ],
  ["Neem","Azadirachta indica"  ],
  ["Nepali hog plum","Choerospondias axillaris"  ],
  ["Nipa palm fruit","Nypa fruticans"  ],
  ["Nutmeg fruit","Myristica fragrans"  ],
  ["Oklahoma plum","Prunus gracilis"  ],
  ["Olosapo","Couepia polyandra"  ],
  ["Oshima cherry","Prunus speciosa"  ],
  ["Otaheite gooseberry","Phyllanthus acidus"  ],
  ["Pacific plum","Prunus subcordata"  ],
  ["Paho mango","Mangifera altissima"  ],
  ["Paperbark satinash fruit","Syzygium papyraceum"  ],
  ["Partridgeberry","Mitchella repens"  ],
  ["Peach","Prunus persica"  ],
  ["Peach palm fruit","Bactris gasipaes"  ],
  ["Peanut butter fruit","Bunchosia glandulifera"  ],
  ["Pequi","Caryocar brasiliense"  ],
  ["Phalsa","Grewia asiatica"  ],
  ["Pigeon plum","Coccoloba diversifolia"  ],
  ["Pili","Canarium ovatum"  ],
  ["Pin cherry","Prunus pensylvanica"  ],
  ["Pink satinash fruit","Syzygium sayeri"  ],
  ["Pitanga","Eugenia uniflora"  ],
  ["Pitomba","Talisia esculenta"  ],
  ["Prunus alaica","Prunus alaica"  ],
  ["Prunus bifrons","Prunus bifrons"  ],
  ["Prunus cortapico","Prunus cortapico"  ],
  ["Pulasan","Nephelium ramboutan-ake"  ],
  ["Queen palm fruit","Syagrus romanzoffiana"  ],
  ["Rambutan","Nephelium lappaceum"  ],
  ["Red bush apple","Syzygium suborbiculare"  ],
  ["Rex satinash fruit","Syzygium apodophyllum"  ],
  ["Riberry","Syzygium luehmannii"  ],
  ["River cherry","Syzygium tierneyanum"  ],
  ["Russian olive","Elaeagnus angustifolia"  ],
  ["Sabal palm fruit","Sabal palmetto"  ],
  ["Sageretia","Sageretia theezans"  ],
  ["Sand cherry","Prunus pumila"  ],
  ["Sansapote","Licania platypus"  ],
  ["Sargent's cherry","Prunus sargentii"  ],
  ["Savannah cherry","Eugenia calycina"  ],
  ["Saw palmetto fruit","Serenoa repens"  ],
  ["Sea apple","Syzygium grande"  ],
  ["Sea coconut","Lodoicea maldivica"  ],
  ["Sea grape","Coccoloba uvifera"  ],
  ["Shoebutton ardisia","Ardisia elliptica"  ],
  ["Short-stemmed plum","Prunus brachypetala"  ],
  ["Siberian apricot","Prunus sibirica"  ],
  ["Silver almond","Prunus argentea"  ],
  ["Silver buffaloberry","Shepherdia argentea"  ],
  ["Silver date palm fruit","Phoenix sylvestris"  ],
  ["Silver peanut butter fruit","Bunchosia argentea"  ],
  ["Silverberry","Elaeagnus commutata"  ],
  ["Sloe","Prunus spinosa"  ],
  ["Smooth stone peach","Prunus mira"  ],
  ["Soh-sang","Elaeagnus latifolia"  ],
  ["Sour cherry","Prunus cerasus"  ],
  ["Sour cherry","Syzygium corynanthum"  ],
  ["Sourplum","Ximenia afra"  ],
  ["Spanish cherry","Mimusops elengi"  ],
  ["Spanish lime","Melicoccus bijugatus"  ],
  ["Staghorn sumac","Rhus typhina"  ],
  ["Swamp maire","Syzygium maire"  ],
  ["Syzygium alternifolium","Syzygium alternifolium"  ],
  ["Syzygium calophyllifolium","Syzygium calophyllifolium"  ],
  ["Syzygium calubcob","Syzygium calubcob"  ],
  ["Syzygium cordatilimbum","Syzygium cordatilimbum"  ],
  ["Syzygium crassipes","Syzygium crassipes"  ],
  ["Syzygium eucalyptoides","Syzygium eucalyptoides"  ],
  ["Syzygium gilletii","Syzygium gilletii"  ],
  ["Syzygium incarnatum","Syzygium incarnatum"  ],
  ["Syzygium mananquil","Syzygium mananquil"  ],
  ["Syzygium masukuense","Syzygium masukuense"  ],
  ["Syzygium micklethwaitii","Syzygium micklethwaitii"  ],
  ["Syzygium multipetalum","Syzygium multipetalum"  ],
  ["Syzygium nervosum","Syzygium nervosum"  ],
  ["Syzygium owariense","Syzygium owariense"  ],
  ["Syzygium scortechinii","Syzygium scortechinii"  ],
  ["Syzygium simile","Syzygium simile"  ],
  ["Syzygium xanthophyllum","Syzygium xanthophyllum"  ],
  ["Taiwan cherry","Prunus campanulata"  ],
  ["Tamarind-plum","Dialium indum"  ],
  ["Tangut Almond","Prunus tangutica"  ],
  ["Tapia","Uapaca bojeri"  ],
  ["Texas almond","Prunus minutiflora"  ],
  ["Texas peach","Prunus texana"  ],
  ["Tianshan cherry","Prunus tianshanica"  ],
  ["Velvet tamarind","Dialium cochinchinense"  ],
  ["Viagra palm fruit","Calamus erectus"  ],
  ["Water apple","Syzygium jambos"  ],
  ["Water berry","Syzygium cordatum"  ],
  ["Water pear","Syzygium guineense"  ],
  ["Watery rose apple","Syzygium aqueum"  ],
  ["Wax apple","Syzygium samarangense"  ],
  ["White apple","Syzygium forte"  ],
  ["White aspen berry","Acronychia oblongifolia"  ],
  ["White satinash fruit","Syzygium puberulum"  ],
  ["Wild cherry","Prunus avium"  ],
  ["Wild Himalayan cherry","Prunus cerasoides"  ],
  ["Wild jujube","Ziziphus lotus"  ],
  ["Wild peach","Terminalia carpentariae"  ],
  ["Willow leaf cherry","Prunus incana"  ],
  ["Winter-flowering cherry","Prunus Ã— subhirtella"  ],
  ["Wongi","Manilkara kauki"  ],
  ["Wooly jelly palm fruit","Butia eriospatha"  ],
  ["Xiao putao","Syzygium acuminatissimum"  ],
  ["Yangmei","Myrica rubra"  ],
  ["Yatay palm fruit","Butia yatay"  ],
  ["Yellow mombin","Spondias mombin"  ],
  ["Yellow plum","Ximenia americana"  ],
  ["Yoshino cherry",""  ],
  ["Ziziphus budhensis","Ziziphus budhensis"  ],
  ["Ziziphus incurva","Ziziphus incurva"  ],
  ["Zunna berry","Ziziphus rugosa"  ],
  ["Zwetschge",""  ],
  ["Abiu","Pouteria caimito"  ],
  ["Aboirana","Pouteria venosa"  ],
  ["American black elderberry","Sambucus canadensis"  ],
  ["American persimmon","Diospyros virginiana"  ],
  ["American red elderberry","Sambucus pubens"  ],
  ["Apple berry","Billardiera scandens"  ],
  ["Arabian coffee","Coffea arabica"  ],
  ["Araza","Eugenia stipitata"  ],
  ["Babaco",""  ],
  ["Banana","Musa acuminata"  ],
  ["Banana passionfruit","Passiflora tarminiana"  ],
  ["Barberry","Berberis vulgaris"  ],
  ["Bearberry","Arctostaphylos uva-ursi"  ],
  ["Bell apple","Passiflora nitida"  ],
  ["Bengal currant","Carissa carandas"  ],
  ["Bilberry","Vaccinium myrtillus"  ],
  ["Bilberry cactus fruit","Myrtillocactus geometrizans"  ],
  ["Bilimbi","Averrhoa bilimbi"  ],
  ["Black currant","Ribes nigrum"  ],
  ["Black sapote","Diospyros nigra"  ],
  ["Blue passionfruit","Passiflora caerulea"  ],
  ["Blue sweet calabash","Passiflora morifolia"  ],
  ["Blueberry","Vaccinium corymbosum"  ],
  ["Bola verde","Anisocapparis speciosa"  ],
  ["Bolivian fuchsia fruit","Fuchsia boliviana"  ],
  ["Bolwarra","Eupomatia laurina"  ],
  ["Bombona","Solanum pachyandrum"  ],
  ["Boroj","Alibertia patinoi"  ],
  ["Brazil cherry","Eugenia brasiliensis"  ],
  ["Brazilian guava","Psidium guineense"  ],
  ["Burahol","Stelechocarpus burahol"  ],
  ["Bushveld bluebush","Diospyros lycioides"  ],
  ["Cactus pineapple","Selenicereus setaceus"  ],
  ["Cainito","Chrysophyllum cainito"  ],
  ["Calabur fruit","Muntingia calabura"  ],
  ["Cambuci","Campomanesia phaea"  ],
  ["Camu camu","Myrciaria dubia"  ],
  ["Canistel","Pouteria campechiana"  ],
  ["Cape gooseberry","Physalis peruviana"  ],
  ["Cattley guava","Psidium cattleyanum"  ],
  ["Ceylon gooseberry","Dovyalis hebecarpa"  ],
  ["Chilean guava","Ugni molinae"  ],
  ["Chinese gooseberry","Actinidia chinensis"  ],
  ["Cinnamon apple","Pouteria hypoglauca"  ],
  ["Conkerberry","Carissa spinarum"  ],
  ["Costa Rican guava","Psidium friedrichsthalianum"  ],
  ["Costa Rican pitahaya","Selenicereus costaricensis"  ],
  ["Cranberry","Vaccinium macrocarpon"  ],
  ["Crimson passionfruit","Passiflora cinnabarina"  ],
  ["Cuajilote","Parmentiera aculeata"  ],
  ["Curuba","Passiflora mixta"  ],
  ["Darwin's barberry","Berberis darwinii"  ],
  ["Date-plum","Diospyros lotus"  ],
  ["Davidson's plum","Davidsonia jerseyana"  ],
  ["Desert passionfruit","Passiflora pentaschista"  ],
  ["Dragon fruit","Selenicereus undatus"  ],
  ["Dutchman's laudanum","Passiflora rubra"  ],
  ["Eggfruit","Lucuma campechiana"  ],
  ["Elderberry","Sambucus nigra"  ],
  ["Fe'i banana",""  ],
  ["Feijoa","Feijoa sellowiana"  ],
  ["Fox grape","Vitis labrusca"  ],
  ["Garlic passionfruit","Passiflora loefgrenii"  ],
  ["Giant granadilla","Passiflora quadrangularis"  ],
  ["Giant highland banana","Musa ingens"  ],
  ["Glenniea philippinensis","Glenniea philippinensis"  ],
  ["Golden kiwifruit",""  ],
  ["Gooseberry","Ribes uva-crispa"  ],
  ["Grape","Vitis vinifera"  ],
  ["Green sapote","Pouteria viridis"  ],
  ["Guab","Diospyros malabarica"  ],
  ["Guava","Psidium guajava"  ],
  ["Hardy kiwi","Actinidia arguta"  ],
  ["Honeyberry","Lonicera caerulea"  ],
  ["Honeysuckle","Lonicera periclymenum"  ],
  ["Huckleberry","Vaccinium ovatum"  ],
  ["Jabuticaba","Plinia cauliflora"  ],
  ["Kei apple","Dovyalis afra"  ],
  ["Kiwifruit",""  ],
  ["Kolomicta","Actinidia kolomikta"  ],
  ["Kubal","Willughbeia sarawacensis"  ],
  ["Lingonberry","Vaccinium vitis-idaea"  ],
  ["LÃºcuma","Pouteria lucuma"  ],
  ["Malabar plum","Syzygium jambos"  ],
  ["Mammee","Mammea americana"  ],
  ["Mandacaru","Cereus jamacaru"  ],
  ["Mangaba","Hancornia speciosa"  ],
  ["Maqui berry","Aristotelia chilensis"  ],
  ["Maracuja Bravo","Passiflora gibertii"  ],
  ["Maracuja Mochila","Passiflora cincinnata"  ],
  ["Maracuja Redondo","Passiflora picturata"  ],
  ["Mayapple","Podophyllum peltatum"  ],
  ["Maypop","Passiflora incarnata"  ],
  ["Midgen berry","Austromyrtus dulcis"  ],
  ["MortiÃ±o","Vaccinium floribundum"  ],
  ["Mountain granadilla","Passiflora ambigua"  ],
  ["Mountain papaya","Vasconcellea pubescens"  ],
  ["Muscadine","Vitis rotundifolia"  ],
  ["Musho","Jaltomata cajacayensis"  ],
  ["Naranjilla","Solanum quitoense"  ],
  ["Native currant","Acrotriche depressa"  ],
  ["New Zealand passionfruit","Passiflora tetrandra"  ],
  ["Nipple beehive cactus fruit","Coryphantha macromeris"  ],
  ["Ocoki","Pouteria ucuqui"  ],
  ["Ooray","Davidsonia pruriens"  ],
  ["Oowel paap","Passiflora serratifolia"  ],
  ["Oregon grape","Mahonia aquifolium"  ],
  ["Oubli fruit","Pentadiplandra brazzeana"  ],
  ["Papaya","Carica papaya"  ],
  ["Passiflora ampullacea","Passiflora ampullacea"  ],
  ["Passiflora platyloba","Passiflora platyloba"  ],
  ["Passionfruit","Passiflora edulis"  ],
  ["Pepino","Solanum muricatum"  ],
  ["Perfumed passionfruit","Passiflora vitifolia"  ],
  ["Persimmon","Diospyros kaki"  ],
  ["Peruvian apple cactus fruit","Cereus repandus"  ],
  ["Pink banana","Musa velutina"  ],
  ["Pitahaya de ocampo","Selenicereus ocamponis"  ],
  ["Pitaya-da-guatemala","Selenicereus guatemalensis"  ],
  ["Pitomba-da-bahia","Eugenia luschnathiana"  ],
  ["Planchonella maclayana","Planchonella maclayana"  ],
  ["Plantain","Musa balbisiana"  ],
  ["Pomegranate","Punica granatum"  ],
  ["Poro poro","Passiflora pinnatistipula"  ],
  ["Prickly pear fruit","Opuntia ficus-indica"  ],
  ["Purple apple-berry","Billardiera longiflora"  ],
  ["Purple guava","Psidium rufum"  ],
  ["Purple kiwi","Actinidia melanandra"  ],
  ["Puru","Alibertia edulis"  ],
  ["Red banana passionfruit","Passiflora antioquiensis"  ],
  ["Red currant","Ribes rubrum"  ],
  ["Red huckleberry","Vaccinium parvifolium"  ],
  ["Red passionfruit","Passiflora manicata"  ],
  ["Rukam","Flacourtia rukam"  ],
  ["Saguaro fruit","Carnegiea gigantea"  ],
  ["Salal","Gaultheria shallon"  ],
  ["Scarlet passionfruit","Passiflora coccinea"  ],
  ["Sea anemone passionfruit","Passiflora actinia"  ],
  ["Sea buckthorn","Hippophae rhamnoides"  ],
  ["Selenicereus stenopterus","Selenicereus stenopterus"  ],
  ["Small-leaved fuchsia","Fuchsia microphylla"  ],
  ["Small-leaved myrtle berry","Archirhodomyrtus beckleri"  ],
  ["Smooth davidson's plum","Davidsonia johnsonii"  ],
  ["Solomon's plume","Maianthemum racemosum"  ],
  ["South American sapote","Quararibea cordata"  ],
  ["Star fruit","Averrhoa carambola"  ],
  ["Stinking passionfruit","Passiflora foetida"  ],
  ["Strawberry tree fruit","Arbutus unedo"  ],
  ["Sugar plum","Uapaca kirkiana"  ],
  ["Swartbas","Diospyros whyteana"  ],
  ["Sweet apple-berry","Billardiera cymosa"  ],
  ["Sweet calabash","Passiflora maliformis"  ],
  ["Sweet granadilla","Passiflora ligularis"  ],
  ["Tamarillo","Solanum betaceum"  ],
  ["Texas persimmon","Diospyros texana"  ],
  ["Tumbo","Passiflora tripartita"  ],
  ["Velvet apple","Diospyros blancoi"  ],
  ["Wampee","Clausena lansium"  ],
  ["Water lemon","Passiflora laurifolia"  ],
  ["White passionfruit","Passiflora subpeltata"  ],
  ["Wild orange","Capparis mitchellii"  ],
  ["Wild passionfruit","Passiflora membranacea"  ],
  ["Winged-stem passionfruit","Passiflora alata"  ],
  ["Wolfberry","Lycium barbarum"  ],
  ["Wooly abiu","Pouteria torta"  ],
  ["Yellow dragon fruit","Selenicereus megalanthus"  ],
  ["Yellow granadilla","Passiflora edulis f flavicarpa"  ],
  ["African baobab fruit","Adansonia digitata"  ],
  ["Australian baobab fruit","Adansonia gregorii"  ],
  ["Bael","Aegle marmelos"  ],
  ["Bailan melon",""  ],
  ["Banana melon","Cucumis melo 'Banana'"  ],
  ["Banana yucca","Yucca baccata"  ],
  ["Canary melon",""  ],
  ["Cassabanana","Sicana odorifera"  ],
  ["Citron melon","Citrullus amarus"  ],
  ["Crane melon","Cucumis melo 'Crane'"  ],
  ["Crenshaw melon","Cucumis melo 'Crenshaw'"  ],
  ["Cucumis prophetarum","Cucumis prophetarum"  ],
  ["Doub palm fruit","Borassus flabellifer"  ],
  ["European cantaloupe","Cucumis melo var. cantalupensis"  ],
  ["Fony baobab fruit","Adansonia rubrostipa"  ],
  ["Gaya melon","Cucumis melo 'Gaya'"  ],
  ["Honeydew melon","Cucumis melo var. inodorus"  ],
  ["Hydnora abyssinica","Hydnora abyssinica"  ],
  ["Jackal food","Hydnora africana"  ],
  ["JÃ­cara","Crescentia cujete"  ],
  ["Kajari melon","Cucumis melo 'Kajari'"  ],
  ["Kiwano","Cucumis metuliferus"  ],
  ["Kiwano rund","Cucumis metuliferus var. rund"  ],
  ["Kolkhoznitsa melon","Cucumis melo 'Kolkhoznitsa'"  ],
  ["Limelon","Cucumis melo"  ],
  ["Mirza melon","Cucumis melo 'Mirza'"  ],
  ["Muskmelon","Cucumis melo"  ],
  ["Natal orange","Strychnos spinosa"  ],
  ["North American cantaloupe",""  ],
  ["Oriental melon",""  ],
  ["Santa Claus melon",""  ],
  ["Sprite melon","Cucumis melo 'Sprite'"  ],
  ["Tigger melon","Cucumis melo 'Tigger'"  ],
  ["Watermelon","Citrullus lanatus"  ],
  ["Wood-apple","Limonia acidissima"  ],
  ["African cherry orange","Citropsis articulata"  ],
  ["Amanatsu",""  ],
  ["Bajoura citron",""  ],
  ["Bergamot orange","Citrus bergamia"  ],
  ["Bitter orange",""  ],
  ["Blood lime",""  ],
  ["Blood orange",""  ],
  ["Buddha's hand",""  ],
  ["Calamansi",""  ],
  ["Cara Cara navel orange",""  ],
  ["Centennial variegated kumquat","Citrus margaritaÂ 'Centennial Variegated'"  ],
  ["Citron","Citrus medica"  ],
  ["Clementine","Citrus — clementina"  ],
  ["Desert lime","Citrus glauca"  ],
  ["Etrog","Citrus medica var. ethrog"  ],
  ["Finger lime","Citrus australasica"  ],
  ["Florentine citron","Citrus — limonimedica"  ],
  ["Grapefruit","Citrus — aurantium f. aurantium"  ],
  ["Haruka","Citrus tamurana — natsudaidai"  ],
  ["Hyuganatsu","Citrus tamurana"  ],
  ["Ichang papeda","Citrus cavaleriei"  ],
  ["Iyokan","Citrus — iyo"  ],
  ["Jiangsu kumquat","Citrus obovata"  ],
  ["Kabosu","Citrus sphaerocarpa"  ],
  ["Kaffir lime","Citrus hystrix"  ],
  ["Kanpei","Citrus reticulata 'Kanpei'"  ],
  ["Kawachi bankan","Citrus kawachiensis"  ],
  ["Key lime",""  ],
  ["Kinkoji unshiu",""  ],
  ["Kinnow",""  ],
  ["Kiyomi",""  ],
  ["Kobayashi mikan",""  ],
  ["Koji orange","Citrus leiocarpa"  ],
  ["Kuchinotsu ",""  ],
  ["Kumquat","Citrus japonica"  ],
  ["Lemon",""  ],
  ["Lime",""  ],
  ["Limeberry","Triphasia trifolia"  ],
  ["Limequat",""  ],
  ["Mandarin orange","Citrus reticulata"  ],
  ["Mangshanyegan","Citrus mangshanensis"  ],
  ["Melogold",""  ],
  ["Meyer lemon",""  ],
  ["Micrantha",""  ],
  ["Moro blood orange",""  ],
  ["Myrtle-leaved orange","Citrus myrtifolia"  ],
  ["ÅŒgonkan","Citrus flaviculpus"  ],
  ["Ojai pixie","Citrus reticulataÂ 'Ojai Pixie'"  ],
  ["Orange",""  ],
  ["Oroblanco",""  ],
  ["Oval kumquat","Citrus margarita"  ],
  ["Pomelo","Citrus maxima"  ],
  ["Pompia","Citrus medicaÂ var. tuberosa"  ],
  ["Ponderosa lemon",""  ],
  ["Rangpur",""  ],
  ["Round lime","Citrus australis"  ],
  ["Sanguinello blood orange",""  ],
  ["Satsuma mandarin","Citrus unshiu"  ],
  ["Shangjuan",""  ],
  ["Shonan gold",""  ],
  ["Sudachi","Citrus sudachi"  ],
  ["Sweet limetta","Citrus limetta"  ],
  ["Sweet orange",""  ],
  ["Taiwan tangerine",""  ],
  ["Tangelo",""  ],
  ["Tangerine",""  ],
  ["Tangor",""  ],
  ["Tarocco blood orange",""  ],
  ["Ugli fruit",""  ],
  ["Volkamer lemon","Citrus volkameriana"  ],
  ["Yuzu",""  ],
  ["African custard-apple","Annona senegalensis"  ],
  ["American beautyberry","Callicarpa americana"  ],
  ["American red raspberry","Rubus strigosus"  ],
  ["Annona aurantiaca","Annona aurantiaca"  ],
  ["Annona conica","Annona conica"  ],
  ["Annona coriacea","Annona coriacea"  ],
  ["Annona cornifolia","Annona cornifolia"  ],
  ["Annona jahnii","Annona jahnii"  ],
  ["Annona longiflora","Annona longiflora"  ],
  ["Annona nutans","Annona nutans"  ],
  ["Annona paludosa","Annona paludosa"  ],
  ["Annona stenophylla","Annona stenophylla"  ],
  ["Annonilla","Annona nitida"  ],
  ["Aratincum do Para","Annona sericea"  ],
  ["Arctic raspberry","Rubus arcticus"  ],
  ["Armenian blackberry","Rubus armeniacus"  ],
  ["Atemoya","Annona squamosa — Annona cherimola"  ],
  ["Atherton raspberry","Rubus probus"  ],
  ["Atibulnak","Rubus pectinellus"  ],
  ["Balloon berry","Rubus illecebrosus"  ],
  ["Beach strawberry","Fragaria chiloensis"  ],
  ["Beach sugar apple","Annona salzmannii"  ],
  ["Birib","Annona mucosa"  ],
  ["Black mulberry","Morus nigra"  ],
  ["Black raspberry","Rubus occidentalis"  ],
  ["Blackberry","Rubus allegheniensis"  ],
  ["Boysenberry","Rubus ursinus — Rubus idaeus"  ],
  ["California blackberry","Rubus ursinus"  ],
  ["Cawesh","Annona scleroderma"  ],
  ["Cherimoya","Annona cherimola"  ],
  ["Chinese bramble berry","Rubus tricolor"  ],
  ["Cloudberry","Rubus chamaemorus"  ],
  ["Creeping raspberry","Rubus hayata-koidzumii"  ],
  ["Cudrang","Maclura tricuspidata"  ],
  ["Custard apple","Annona reticulata"  ],
  ["Cutleaf evergreen blackberry","Rubus laciniatus"  ],
  ["Delicious raspberry","Rubus deliciosus"  ],
  ["Dewberry","Rubus flagellaris"  ],
  ["Dwarf red blackberry","Rubus pubescens"  ],
  ["Elephant apple","Dillenia indica"  ],
  ["Elmleaf blackberry","Rubus ulmifolius"  ],
  ["Emu berry","Grewia retusifolia"  ],
  ["European dewberry","Rubus caesius"  ],
  ["European red raspberry","Rubus idaeus"  ],
  ["Five-leaved bramble berry","Rubus pedatus"  ],
  ["Garden dewberry","Rubus aboriginum"  ],
  ["Golden Himalayan raspberry","Rubus ellipticus"  ],
  ["Gummy Bear fruit","Cecropia peltata"  ],
  ["Gympie-gympie fruit","Dendrocnide moroides"  ],
  ["Hawaiian raspberry","Rubus hawaiensis"  ],
  ["Ilama","Annona diversifolia"  ],
  ["Japanese bramble berry","Rubus parvifolius"  ],
  ["Korean blackberry","Rubus coreanus"  ],
  ["Korean raspberry","Rubus crataegifolius"  ],
  ["Kousa dogwood fruit","Cornus kousa"  ],
  ["Loganberry","Rubus — loganobaccus"  ],
  ["Marolo","Annona crassiflora"  ],
  ["Mock strawberry","Potentilla indica"  ],
  ["Molucca bramble berry","Rubus moluccanus"  ],
  ["Molucca raspberry","Rubus sieboldii"  ],
  ["Mora comÃºn","Rubus adenotrichos"  ],
  ["Mora de Castilla","Rubus glaucus"  ],
  ["Mountain raspberry","Rubus fraxinifolius"  ],
  ["Mountain soursop","Annona montana"  ],
  ["Mysore raspberry","Rubus niveus"  ],
  ["Nepalese raspberry","Rubus nepalensis"  ],
  ["Pennsylvania blackberry","Rubus pensilvanicus"  ],
  ["Pineberry","Fragaria virginiana — chiloensis"  ],
  ["Pond apple","Annona glabra"  ],
  ["Purple-flowered raspberry","Rubus odoratus"  ],
  ["Red mulberry","Morus rubra"  ],
  ["Rose hip","Rosa sp."  ],
  ["Roseleaf bramble berry","Rubus rosifolius"  ],
  ["Rubus adenophorus","Rubus adenophorus"  ],
  ["Rubus biflorus","Rubus biflorus"  ],
  ["Rubus corchorifolius","Rubus corchorifolius"  ],
  ["Rubus gratus","Rubus gratus"  ],
  ["Rubus roseus","Rubus roseus"  ],
  ["Rubus xanthocarpus","Rubus xanthocarpus"  ],
  ["Salmonberry","Rubus spectabilis"  ],
  ["Sawtooth blackberry","Rubus argutus"  ],
  ["Smooth blackberry","Rubus canadensis"  ],
  ["Snow raspberry","Rubus nivalis"  ],
  ["Soncoya","Annona purpurea"  ],
  ["Soursop","Annona muricata"  ],
  ["Stone bramble berry","Rubus saxatilis"  ],
  ["Strawberry",""  ],
  ["Sugar-apple","Annona squamosa"  ],
  ["Tasmanian alpine raspberry","Rubus gunnianus"  ],
  ["Tataramoa","Rubus cissoides"  ],
  ["Tayberry",""  ],
  ["Thimbleberry","Rubus parviflorus"  ],
  ["Susung-kalabaw","Uvaria rufa"  ],
  ["White bark raspberry","Rubus leucodermis"  ],
  ["White mulberry","Morus alba"  ],
  ["White-stemmed bramble","Rubus cockburnianus"  ],
  ["Wild cherimoya","Annona hypoglauca"  ],
  ["Wild strawberry","Fragaria vesca"  ],
  ["Wineberry","Rubus phoenicolasius"  ],
  ["Youngberry","Rubus caesiusÂ 'Youngberry'"  ],
  ["African peach","Nauclea latifolia"  ],
  ["Antipolo","Artocarpus blancoi"  ],
  ["Artocarpus glaucus","Artocarpus glaucus"  ],
  ["Artocarpus lowii","Artocarpus lowii"  ],
  ["Two-colored jackfruit","Artocarpus styracifolius"  ],
  ["Bondon","Artocarpus brevipedunculatus"  ],
  ["Breadfruit","Artocarpus altilis"  ],
  ["Breadnut","Artocarpus camansi"  ],
  ["Cempedak","Artocarpus integer"  ],
  ["Ceylon breadfruit","Artocarpis nobilis"  ],
  ["Chaplaish","Artocarpus chama"  ],
  ["Clown fig","Ficus aspera"  ],
  ["Cluster fig","Ficus racemosa"  ],
  ["Desert fig","Ficus platypoda"  ],
  ["Dugdug","Artocarpus mariannensis"  ],
  ["Duguetia confinis","Duguetia confinis"  ],
  ["Duguetia spixiana","Duguetia spixiana"  ],
  ["Dye fig","Ficus tinctoria"  ],
  ["Entawak","Artocarpus anisophyllus"  ],
  ["False pineapple","Ananas macrodontes"  ],
  ["Ficus carrii","Ficus carrii"  ],
  ["Ficus insipida","Ficus insipida"  ],
  ["Ficus neriifolia","Ficus neriifolia"  ],
  ["Ficus parietalis","Ficus parietalis"  ],
  ["Ficus simplicissima","Ficus simplicissima"  ],
  ["Ficus sinuata","Ficus sinuata"  ],
  ["Ficus ulmifolia","Ficus ulmifolia"  ],
  ["Ficus wassa","Ficus wassa"  ],
  ["Fig","Ficus carica"  ],
  ["Hala fruit","Pandanus tectorius"  ],
  ["Jackfruit","Artocarpus heterophyllus"  ],
  ["Japanese fig","Ficus erecta"  ],
  ["Keledang","Artocarpus lanceifolius"  ],
  ["Kesusu","Prainea limpato"  ],
  ["Kwai muk","Artocarpus parvus"  ],
  ["Marang","Artocarpus odoratissimus"  ],
  ["Monkey fruit","Artocarpus lacucha"  ],
  ["Monkey jackfruit","Artocarpus rigidus"  ],
  ["Monstera deliciosa","Monstera deliciosa"  ],
  ["Noni","Morinda citrifolia"  ],
  ["Oakleaf fig","Ficus montana"  ],
  ["Peluntan","Artocarpus sericicarpus"  ],
  ["Pineapple","Ananas comosus"  ],
  ["Pingan","Artocarpus sarawakensis"  ],
  ["Pinkglow pineapple","Ananas comosusÂ 'Pinkglow'"  ],
  ["Pudau","Artocarpus kemando"  ],
  ["Red fruit","Pandanus conoideus"  ],
  ["River sandpaper fig","Ficus capreifolia"  ],
  ["Sampang","Artocarpus gomezianus"  ],
  ["Sandpaper fig","Ficus coronata"  ],
  ["Strangler fig","Ficus aurea"  ],
  ["Sweet sandpaper fig","Ficus opposita"  ],
  ["Sycamore fig","Ficus sycomorus"  ],
  ["Tamaran","Artocarpus tamaran"  ],
  ["Terap hitam","Artocarpus scortechinii"  ],
  ["Terap nasi","Artocarpus elasticus"  ],
  ["Tilap","Artocarpus teysmannii"  ],
  ["White fig","Ficus virens"  ],
  ["White kwai muk","Artocarpus hypargyreus"  ],
  ["White sandpaper fig","Ficus fraseri"  ],
  ["Wild fig","Ficus palmata"  ],
  ["Wild jack","Artocarpus hirsutus"  ],
  ["Achacha","Garcinia humilis"  ],
  ["Ackee","Blighia sapida"  ],
  ["Aglaia teysmanniana","Aglaia teysmanniana"  ],
  ["Asam gelugur","Garcinia atroviridis"  ],
  ["Asam kelubi","Eleiodoxa conferta"  ],
  ["Bacupari","Garcinia brasiliensis"  ],
  ["Bacuri","Platonia insignis"  ],
  ["Bemange","Cola urceolata"  ],
  ["Binukaw","Garcinia binucao"  ],
  ["Black apple","Pouteria australis"  ],
  ["Blue tongue","Melastoma affine"  ],
  ["Boquila","Boquila trifoliolata"  ],
  ["Burmese grape","Baccaurea ramiflora"  ],
  ["Button mangosteen","Garcinia prainiana"  ],
  ["Cacao","Theobroma cacao"  ],
  ["Charichuelo","Garcinia madruno"  ],
  ["Chocolate vine fruit","Akebia quinata"  ],
  ["Copperleaf snowberry","Gaultheria hispida"  ],
  ["Courbaril","Hymenaea courbaril"  ],
  ["Cowa mangosteen","Garcinia cowa"  ],
  ["Durian","Durio zibethinus"  ],
  ["Durio oxleyanus","Durio oxleyanus"  ],
  ["Eastern teaberry","Gaultheria procumbens"  ],
  ["Gamboge","Garcinia morella"  ],
  ["Garcinia afzelii","Garcinia afzelii"  ],
  ["Garcinia cambogia","Garcinia gummi-gutta"  ],
  ["Garcinia costata","Garcinia costata"  ],
  ["Garcinia forbesii","Garcinia forbesii"  ],
  ["Garcinia magnifolia","Garcinia magnifolia"  ],
  ["Garcinia pseudoguttifera","Garcinia pseudoguttifera"  ],
  ["Jentik","Baccaurea polyneura"  ],
  ["Keluak","Pangium edule"  ],
  ["Kokum","Garcinia indica"  ],
  ["Kola nut","Cola nitida"  ],
  ["Kundong","Garcinia parvifolia"  ],
  ["Langgir","Xanthophyllum amoenum"  ],
  ["Langsat","Lansium domesticum"  ],
  ["Langsat","Lansium parasiticum"  ],
  ["Lardizabala","Lardizabala biternata"  ],
  ["Lemon drop mangosteen","Garcinia intermedia"  ],
  ["LuÃ³hÃ n guÇ’","Siraitia grosvenorii"  ],
  ["Madan","Garcinia schomburgkiana"  ],
  ["Mangosteen","Garcinia mangostana"  ],
  ["Menteng","Baccaurea racemosa"  ],
  ["Mountain snowberry","Gaultheria depressa"  ],
  ["Mundu","Garcinia dulcis"  ],
  ["Pawpaw","Asimina triloba"  ],
  ["Red salak","Salacca affinis"  ],
  ["Salak","Salacca zalacca"  ],
  ["Santol","Sandoricum koetjape"  ],
  ["Seashore mangosteen","Garcinia celebica"  ],
  ["Small-leaved tamarind","Diploglottis campbellii"  ],
  ["Spanish tamarind","Vangueria madagascariensis"  ],
  ["Terengganu cherry","Lepisanthes alata"  ],
  ["Toad tree fruit","Tabernaemontana elegans"  ],
  ["Trichosanthes beccariana","Trichosanthes beccariana"  ],
  ["Utu","Saba senegalensis"  ],
  ["Vanilla","Vanilla planifolia"  ],
  ["Yantok","Calamus manillensis"  ],
  ["African locust bean","Parkia biglobosa"  ],
  ["Carob","Ceratonia siliqua"  ],
  ["Ice-cream bean","Inga edulis"  ],
  ["Monkeypod","Pithecellobium dulce"  ],
  ["Namu-namu","Cynometra cauliflora"  ],
  ["Tamarind","Tamarindus indica"  ],
  ["Zig-zag vine fruit","Melodorum leichhardtii"  ],
  ["Angular sea-fig","Carpobrotus glaucescens"  ],
  ["Dead man's fingers","Decaisnea fargesii"  ],
  ["Karkalla fruit","Carpobrotus rossii"  ],
  ["Sour fig","Carpobrotus edulis"  ],
  ["Alligator juniper berry","Juniperus deppeana"  ],
  ["Arius","Podocarpus costalis"  ],
  ["Broad-leaved brown pine fruit","Podocarpus dispermus"  ],
  ["Broad-leaved yellowwood fruit","Podocarpus latifolius"  ],
  ["Brown pine fruit","Podocarpus neriifolius"  ],
  ["California juniper berry","Juniperus californica"  ],
  ["Cashew apple","Anacardium occidentale"  ],
  ["Creeping juniper berry","Juniperus horizontalis"  ],
  ["Desert juniper berry","Juniperus osteosperma"  ],
  ["Dwarf plum pine fruit","Podocarpus spinulosus"  ],
  ["East African yellowwood fruit","Podocarpus milanjianus"  ],
  ["Ginkgo","Ginkgo biloba"  ],
  ["Greek juniper berry","Juniperus excelsa"  ],
  ["Himalayan juniper berry","Juniperus recurva"  ],
  ["Juniper berry","Juniperus communis"  ],
  ["Juniperus turbinata","Juniperus turbinata"  ],
  ["Kahikatea","Dacrycarpus dacrydioides"  ],
  ["Koolah","Podocarpus drouynianus"  ],
  ["Manoao","Manoao colensoi"  ],
  ["Mountain juniper berry","Juniperus monticola"  ],
  ["Nageia","Nageia nagi"  ],
  ["Native cherry","Exocarpos cupressiformis"  ],
  ["One-seed juniper berry","Juniperus monosperma"  ],
  ["Pashtun juniper berry","Juniperus seravschanica"  ],
  ["Persian juniper berry","Juniperus polycarpos"  ],
  ["Phoenicean juniper berry","Juniperus phoenicea"  ],
  ["Plum pine fruit","Podocarpus elatus"  ],
  ["Podocarpus","Podocarpus elongatus"  ],
  ["Podocarpus lambertii","Podocarpus lambertii"  ],
  ["Prickly juniper berry","Juniperus oxycedrus"  ],
  ["Prumnopitys","Prumnopitys andina"  ],
  ["Raisin tree fruit","Hovenia dulcis"  ],
  ["Redberry juniper berry","Juniperus coahuilensis"  ],
  ["Rhubarb",""  ],
  ["Rimu","Dacrydium cupressinum"  ],
  ["Rocky Mountain juniper berry","Juniperus scopulorum"  ],
  ["Southern juniper berry",""  ],
  ["Syrian juniper berry","Juniperus drupacea"  ],
  ["Temple juniper berry","Juniperus rigida"  ],
  ["Totara","Podocarpus totara"  ],
  ["Virginian juniper berry","Juniperus virginiana"  ],
  ["Western juniper berry","Juniperus occidentalis"  ],
  ["Yew berry","Taxus baccata"  ],
  ["Yew plum pine fruit","Podocarpus macrophyllus"  ],
  ["Acorns",""  ],
  ["Almonds",""  ],
  ["Andean Walnuts",""  ],
  ["Argan Nuts",""  ],
  ["Baru Nuts",""  ],
  ["Beech Nuts",""  ],
  ["Betel Nuts",""  ],
  ["Bitter Almond",""  ],
  ["Black Walnuts",""  ],
  ["Blanco Almond",""  ],
  ["Brazil Nuts",""  ],
  ["Breadnut",""  ],
  ["Bunya Nut",""  ],
  ["Butternuts",""  ],
  ["Canarium Nut",""  ],
  ["Candle Nuts",""  ],
  ["Caramel Almond",""  ],
  ["Cashews",""  ],
  ["Chestnuts",""  ],
  ["Chilean Hazelnut",""  ],
  ["Chinese Chestnut",""  ],
  ["Dika Nuts",""  ],
  ["English Walnut",""  ],
  ["Filberts",""  ],
  ["Fritz Almonds",""  ],
  ["Gabon Nuts",""  ],
  ["Ginkgo Nuts",""  ],
  ["Green Almonds",""  ],
  ["Hazelnuts",""  ],
  ["Hickory Nuts",""  ],
  ["Jack Nuts",""  ],
  ["Kola Nuts",""  ],
  ["Kurrajong Nuts",""  ],
  ["Lotus Nuts",""  ],
  ["Macadamia Nuts",""  ],
  ["Malabar Chestnut",""  ],
  ["Marcona Almond",""  ],
  ["Mission Almond",""  ],
  ["Mongongo Nuts",""  ],
  ["Monkey Puzzle Nut",""  ],
  ["Oysternut",""  ],
  ["Padre Almond",""  ],
  ["Palm Nuts",""  ],
  ["Paradise Nut",""  ],
  ["Peanuts",""  ],
  ["Pecans",""  ],
  ["Peerless Almond",""  ],
  ["Pignoli Nuts",""  ],
  ["Pili Nut",""  ],
  ["Pine Nuts",""  ],
  ["Pistachios",""  ],
  ["Red Bopple Nut",""  ],
  ["Runner Peanut",""  ],
  ["Saba Nuts",""  ],
  ["Spanish Peanut",""  ],
  ["Tiger Nuts",""  ],
  ["Valencia Peanut",""  ],
  ["Virginia Peanut",""  ],
  ["Water Caltrop",""  ],
  ["sorghum","S. bicolor"  ],
  ["maize","Z. mays"  ],
  ["finger millet","E. coracana"  ],
  ["teff","E. tef"  ],
  ["Asian rice","O. sativa"  ],
  ["African rice","O. glaberrima"  ],
  ["wild rice",""  ],
  ["black fonio","D. iburua"  ],
  ["white fonio","D. exilis"  ],
  ["proso millet","P. miliaceum"  ],
  ["little millet","P. sumatrense"  ],
  ["pearl millet","P. glaucum"  ],
  ["foxtail millet","S. italica"  ],
  ["oat","A. sativa"  ],
  ["barley","H. vulgare"  ],
  ["rye","S. cereale"  ],
  ["triticale",""  ],
  ["wheat","T. aestivum"  ],
  ["durum","T. durum"  ],
  ["einkorn","T. monococcum"  ],
  ["spelt","T. spelta"  ],
  ["kamut","T. turanicum"  ],
  ["emmer","T. turgidum"  ],
  ["Kernza","T. intermedium"  ],
  ["amaranth",""  ],
  ["pitseed goosefoot","C. berlandieri"  ],
  ["kañiwa","C. pallidicaule"  ],
  ["quinoa","C. quinoa"  ],
  ["hanza","B. senegalensis"  ],
  ["chia","S. hispanica"  ],
  ["flax","L. usitatissimum"  ],
  ["breadnut","B. alicastrum"  ],
  ["sesame","S. indicum"  ],
  ["buckwheat","F. esculentum"  ],
  ["peanut (groundnut)","A. hypogaea"  ],
  ["chickpea","C. arietinum"  ],
  ["pea","P. sativum"  ],
  ["Indian beechnut","P. pinnata"  ],
  ["pigeon pea","C. cajan"  ],
  ["soybean","G. max"  ],
  ["runner bean","P. coccineus"  ],
  ["lima bean","P. lunatus"  ],
  ["common bean","P. vulgaris"  ],
  ["moth bean","V.aconitifolia"  ],
  ["adzuki bean","V. angularis"  ],
  ["black gram","V. mungo"  ],
  ["mung bean","V. radiata"  ],
  ["Bambara groundnut","V. subterranea"  ],
  ["cowpea","V. unguiculata"  ],
  ["lentil","L. culinaris"  ],
  ["fava bean","V. faba"  ],
  ["Cempedak",""  ],
  ["Cocoa bean",""  ],
  ["Coffee bean",""  ],
  ["Cumin seed",""  ],
  ["Durian",""  ],
  ["Fox nut",""  ],
  ["Hemp seed",""  ],
  ["Jackfruit",""  ],
  ["Lotus seed",""  ],
  ["Mustard seed",""  ],
  ["Osage orange seed",""  ],
  ["Papaya seed",""  ],
  ["Poppy seed",""  ],
  ["Pomegranate seed",""  ],
  ["Sunflower seed",""  ],
  ["Pumpkin seed",""  ],
  ["Watermelon seed",""  ],
  ["Passion fruit seed",""  ],
  ["Arrowhead elephant ear","Xanthosoma sagittifolium"  ],
  ["Asiatic pennywort","Centella asiatica"  ],
  ["Arugula","Eruca sativa"  ],
  ["Atibulnak","Rubus pectinellus"  ],
  ["Beet greens","Beta vulgaris vulgaris"  ],
  ["Binung","Christella dentata"  ],
  ["Carrot greens","Daucus carota"  ],
  ["Bok choy","Brassica rapa"  ],
  ["Borage greens","Borago officinalis"  ],
  ["Broccoli (leaves / stalks)","Brassica oleracea"  ],
  ["Brooklime","Veronica beccabunga"  ],
  ["Brussels sprouts","Brassica oleracea"  ],
  ["Cabbage","Brassica oleracea"  ],
  ["Caraway leaves","Carum carvi"  ],
  ["Catsear","Hypochaeris radicata"  ],
  ["Celery","Apium graveolens"  ],
  ["Celtuce","Lactuca sativa"  ],
  ["Chaya","Cnidoscolus aconitifolius aconitifolius"  ],
  ["Chili pepper leaves",""  ],
  ["Chickweed","Stellaria"  ],
  ["Chicory","Cichorium intybus"  ],
  ["Chinese mallow","Malva verticillata"  ],
  ["Collard greens","Brassica oleracea"  ],
  ["Common purslane","Portulaca oleracea"  ],
  ["Corn salad","Valerianella locusta"  ],
  ["Cress","Lepidium sativum"  ],
  ["Cucumis prophetarum","Cucumis prophetarum"  ],
  ["Garland Chrysanthemum","Chrysanthemum coronarium"  ],
  ["Ground elder","Aegopodium podagraria"  ],
  ["Dandelion","Taraxacum officinale"  ],
  ["Dill","Anethum graveolens"  ],
  ["Endive","Cichorium endivia"  ],
  ["Fat hen","Chenopodium album"  ],
  ["Fiddlehead","Pteridium aquilinum, Athyrium esculentum"  ],
  ["Fluted pumpkin","Telfairia occidentalis"  ],
  ["Gnetum / Melinjo","Gnetum gnemon"  ],
  ["Golden samphire","Inula crithmoides"  ],
  ["Good King Henry","Chenopodium bonus-henricus"  ],
  ["Grape leaves","Vitis"  ],
  ["Greater plantain","Plantago major"  ],
  ["Jute mallow",""  ],
  ["Melokhia","Corchorus olitorius"  ],
  ["Kai-lan","Brassica rapa (alboglabra)"  ],
  ["Kale","Brassica oleracea (acephala)"  ],
  ["Kalette","Brassica oleracea"  ],
  ["Kerguelen cabbage","Pringlea antiscorbutica"  ],
  ["Komatsuna",""  ],
  ["Kuka","Adansonia"  ],
  ["Lagos bologi","Talinum fruticosum"  ],
  ["Lamb's lettuce","Valerianella locusta"  ],
  ["Lamb's quarters","Chenopodium album"  ],
  ["Land cress","Barbarea verna"  ],
  ["Leaf celery",""  ],
  ["Lettuce","Lactuca sativa"  ],
  ["Lizard's tail","Houttuynia cordata"  ],
  ["Malabar spinach","Basella alba"  ],
  ["Mallow","Malvaceae"  ],
  ["Moringa leaves","Moringa oleifera"  ],
  ["Miner's lettuce (Winter purslane)","Claytonia perfoliata"  ],
  ["Mizuna greens","Brassica rapa (nipposinica)"  ],
  ["Mustard","Sinapis alba"  ],
  ["Napa cabbage","Brassica rapa (pekinensis)"  ],
  ["New Zealand Spinach","Tetragonia tetragonioides"  ],
  ["Orache","Atriplex hortensis"  ],
  ["PapayaÂ leaves","Carica papaya"  ],
  ["Paracress","Acmella oleracea"  ],
  ["Pea (sprouts / leaves)","Lathyrus oleraceus"  ],
  ["Pitogo","Cycas riuminiana"  ],
  ["Poke","Phytolacca americana"  ],
  ["Purple bauhinia / Butterfly tree","Bauhinia purpurea"  ],
  ["Radicchio","Cichorium intybus"  ],
  ["Rapini (broccoli rabe)","Brassica rapa rapa"  ],
  ["Red spinach","Amaranthus dubius"  ],
  ["Royal fern","Osmunda regalis"  ],
  ["Samphire","Crithmum maritimum"  ],
  ["Sculpit / Stridolo","Silene inflata"  ],
  ["Sea beet","Beta vulgaris maritima"  ],
  ["Sea kale","Crambe maritima"  ],
  ["Shepherd's purse","Capsella bursa-pastoris"  ],
  ["Sierra Leone bologi","Crassocephalum biafrae"  ],
  ["Soko","Celosia argentea"  ],
  ["Sorrel","Rumex acetosa"  ],
  ["Sour cabbage","Brassica oleracea"  ],
  ["Spinach","Spinacia oleracea"  ],
  ["Spiny amaranth","Amaranthus spinosus"  ],
  ["Summer purslane","Portulaca oleracea"  ],
  ["Sunset muskmallow","Abelmoschus manihot"  ],
  ["Sweet potato leaves","Ipomoea batatas"  ],
  ["Swiss chard","Beta vulgaris cicla (flavescens)"  ],
  ["Tahitian spinach","Xanthosoma brasiliense"  ],
  ["Taro leaves","Colocasia esculenta"  ],
  ["Tatsoi","Brassica rapa (rosularis)"  ],
  ["TurnipÂ greens","Brassica rapa (rapifera)"  ],
  ["Vegetable fern","Diplazium esculentum"  ],
  ["Vegetable hummingbird","Sesbania grandiflora"  ],
  ["Viagra palm","Calamus erectus"  ],
  ["Watercress","Nasturtium officinale"  ],
  ["Water spinach","Ipomoea aquatica"  ],
  ["Wheatgrass","Triticum aestivum"  ],
  ["Yarrow","Achillea millefolium"  ],
  ["Armenian cucumber",""  ],
  ["Butternut squash","Cucurbita moschata"  ],
  ["Bitter melon / Bitter gourd","Momordica charantia"  ],
  ["Caigua / Achocha","Cyclanthera pedata"  ],
  ["Calabash / Bottle gourd","Lagenaria siceraria"  ],
  ["Calabaza / West Indian pumpkin","Cucurbita moschata"  ],
  ["Chayote","Sechium edule"  ],
  ["Corn/Maize","Zea mays"  ],
  ["Gac","Momordica cochinchinensis"  ],
  ["Galo","Anacolosa frutescens"  ],
  ["Cucamelon / Mouse melon","Melothria scabra"  ],
  ["Cucumber","Cucumis sativus"  ],
  ["Eggplant / Aubergine / Brinjal","Solanum melongena"  ],
  ["Ivy gourd","Coccinia grandis"  ],
  ["Kabocha","Cucurbita maxima"  ],
  ["Kiwano / Horned melon","Cucumis metuliferus"  ],
  ["Kapas-kapas","Telosma procumbens"  ],
  ["Luffa","Luffa cylindrica"  ],
  ["Pumpkin","Cucurbita"  ],
  ["Pointed gourd","Trichosanthes dioica"  ],
  ["Ridged gourd","Luffa acutangula"  ],
  ["Snake gourd","Trichosanthes cucumerina"  ],
  ["Spine gourd  / Kantola","Momordica dioica"  ],
  ["Squash","Cucurbita"  ],
  ["Tinda","Praecitrullus fistulosus"  ],
  ["Tipuho","Artocarpus treculianus"  ],
  ["Tomatillo","Physalis philadelphica"  ],
  ["Tomato","Solanum lycopersicum"  ],
  ["West Indian gherkin","Cucumis anguria"  ],
  ["Water melon","Citrullus lanatus"  ],
  ["Winter melon","Benincasa hispida"  ],
  ["Zucchini / Courgette / Marrow","Cucurbita pepo"  ],
  ["Bell pepper",""  ],
  ["Big Jim pepper",""  ],
  ["Cayenne pepper",""  ],
  ["Friggitello",""  ],
  ["Habanero",""  ],
  ["Hungarian wax pepper",""  ],
  ["Jalapeno",""  ],
  ["New Mexico chile",""  ],
  ["Peperoncino",""  ],
  ["Pimiento",""  ],
  ["Sandia pepper",""  ],
  ["Siling haba",""  ],
  ["Artichoke",""  ],
  ["Banana flower",""  ],
  ["Blue pea / Asian pigeonwings","Clitoria ternatea"  ],
  ["Broccoli","Brassica oleracea"  ],
  ["Broccolini flowers","Brassica oleracea"  ],
  ["Calabaza flower","Cucurbita moschata"  ],
  ["Caper","Capparis spinosa"  ],
  ["Cauliflower","Brassica oleracea"  ],
  ["Himbabao","Broussonetia luzonica"  ],
  ["Pumpkin flower","Cucurbita"  ],
  ["Daylily","Hemerocallis fulva"  ],
  ["Jade vine  / Tayabak","Srtongylodon macrobotrys"  ],
  ["Loroco","Echites panduratus"  ],
  ["Moringa","Moringa oleifera"  ],
  ["Waterblommetjie","Aponogeton distachyos"  ],
  ["Courgette flowers","Cucurbita"  ],
  ["Squash blossoms","Cucurbita"  ],
  ["American groundnut","Apios americana"  ],
  ["Asparagus bean","Vigna unguiculata (sesquipedalis)"  ],
  ["Azuki bean","Vigna angularis"  ],
  ["Black-eyed pea","Vigna unguiculata unguiculata"  ],
  ["Chickpea / Garbanzo","Cicer arietinum"  ],
  ["Common bean","Phaseolus vulgaris"  ],
  ["Drumstick","Moringa oleifera"  ],
  ["Dolichos bean","Lablab purpureus"  ],
  ["Fava bean","Vicia faba"  ],
  ["Green beanÂ (French bean)","Phaseolus vulgaris"  ],
  ["Guar","Cyamopsis tetragonoloba"  ],
  ["Horse gram","Macrotyloma uniflorum"  ],
  ["Hyacinth bean","Lablab purpureus"  ],
  ["Indian pea","Lathyrus sativus"  ],
  ["Lentil","Lens culinaris"  ],
  ["Lima bean","Phaseolus lunatus"  ],
  ["Moth bean","Vigna acontifolia"  ],
  ["Mung bean","Vigna radiata"  ],
  ["Okra","Abelmoschus esculentus"  ],
  ["Pea","Pisum sativum"  ],
  ["Peanut","Arachis hypogaea"  ],
  ["Pigeon pea","Cajanus cajan"  ],
  ["Ricebean","Vigna umbellata"  ],
  ["Runner bean","Phaseolus coccineus"  ],
  ["Snap peaÂ (sugarsnap)","Pisum sativum (macrocarpon)"  ],
  ["Snow peaÂ (mangetout)","Pisum sativum (saccharatum)"  ],
  ["Soybean","Glycine max"  ],
  ["Tepary bean","Phaseolus acutifolius"  ],
  ["Urad bean","Vigna mungo"  ],
  ["Velvet bean","Mucuna pruriens"  ],
  ["Winged bean","Psophocarpus tetragonolobus"  ],
  ["Cardoon","Cynara cardunculus"  ],
  ["Celeriac","Apium graveolens (rapaceum)"  ],
  ["Chives","Allium schoenoprasum"  ],
  ["Elephant garlic","Allium ampeloprasum (ampeloprasum)"  ],
  ["Florence fennel","Foeniculum vulgare (dulce)"  ],
  ["Garlic","Allium sativum"  ],
  ["Garlic chives","Allium tuberosum"  ],
  ["Heart of palm",""  ],
  ["Kohlrabi","Brassica oleracea (gongylodes)"  ],
  ["Kurrat","Allium ampeloprasum (kurrat)"  ],
  ["Landang",""  ],
  ["Lemongrass","Cymbopogon citratus"  ],
  ["Leek","Allium porrum"  ],
  ["Lotus root","Nelumbo nucifera"  ],
  ["Nopal","Opuntia ficus-indica"  ],
  ["Onion","Allium cepa"  ],
  ["Pearl onion","Allium ampeloprasum (sectivum)"  ],
  ["Potato onion","Allium cepa (aggregatum)"  ],
  ["Prussian asparagus","Ornithogalum pyrenaicum"  ],
  ["Sago","Metroxylon sagu, Cycas revoluta"  ],
  ["Spring onion / Scallion","Allium wakegi"  ],
  ["samphire greens",""  ],
  ["Shallot","Allium cepa (aggregatum)"  ],
  ["Welsh onion","Allium fistulosum"  ],
  ["Wild leek","Allium tricoccum"  ],
  ["Manchurian wild rice","Zizania latifolia"  ],
  ["Ahipa","Pachyrhizus ahipa"  ],
  ["Arracacha","Arracacia xanthorrhiza"  ],
  ["Arrowleaf elephant ear","Xanthosoma sagittifolium"  ],
  ["Bamboo shoot","Bambusa vulgaris, Phyllostachys edulis"  ],
  ["Beetroot","Beta vulgaris vulgaris"  ],
  ["Burdock","Arctium lappa"  ],
  ["Broadleaf arrowhead","Sagittaria latifolia"  ],
  ["Camas","Camassia"  ],
  ["Canna","Canna"  ],
  ["Carrot","Daucus carota"  ],
  ["Cassumunar ginger","Zingiber cassumunar"  ],
  ["Cassava","Manihot esculenta"  ],
  ["Chinese artichoke","Stachys affinis"  ],
  ["Chinese ginger","Boesenbergia rotunda"  ],
  ["Daikon","Raphanus sativus (longipinnatus)"  ],
  ["Earthnut pea","Lathyrus tuberosus"  ],
  ["Elephant foot yam","Amorphophallus paeoniifolius"  ],
  ["Ensete","Ensete ventricosum"  ],
  ["Giant swamp taro","Cyrtosperma merkusii"  ],
  ["Giant taro","Alocasia macrorrhizos"  ],
  ["Ginger","Zingiber officinale"  ],
  ["Hamburg parsley","Petroselinum crispum tuberosum"  ],
  ["Horseradish","Armoracia rusticana"  ],
  ["Jerusalem artichoke","Helianthus tuberosus"  ],
  ["Kencur","Kaempferia galanga"  ],
  ["Lesser galangal","Alpinia officinarum"  ],
  ["Mashua","Tropaeolum tuberosum"  ],
  ["Palmyra sprout","Borassus flabellifer"  ],
  ["Parsnip","Pastinaca sativa"  ],
  ["Pignut","Conopodium majus"  ],
  ["East Indian arrowroot","Tacca leontopetaloides"  ],
  ["Potato","Solanum tuberosum"  ],
  ["Prairie turnip","Pediomelum esculentum"  ],
  ["Radish","Raphanus sativus"  ],
  ["Salsify","Tragopogon porrifolius"  ],
  ["Scorzonera","Scorzonera hispanica"  ],
  ["Skirret","Sium sisarum"  ],
  ["Sweet potato (Kumara)","Ipomoea batatas"  ],
  ["Taro","Colocasia esculenta"  ],
  ["Ti","Cordyline fruticosa"  ],
  ["Tigernut","Cyperus esculentus"  ],
  ["Turmeric","Curcuma longa"  ],
  ["Turnip","Brassica rapa (rapifera)"  ],
  ["Ube (Purple yam)","Dioscorea alata"  ],
  ["Ulluco","Ullucus tuberosus"  ],
  ["Wasabi","Wasabia japonica"  ],
  ["Water caltrop","Trapa natans, Trapa bicornis"  ],
  ["Water chestnut","Eleocharis dulcis"  ],
  ["Yam","DioscoreaÃ¢â‚¬â€°[4]"  ],
  ["Yautia horqueta","Xanthosoma caracu"  ],
  ["Aonori","Monostroma, Enteromorpha"  ],
  ["Arame","Eisenia bicyclis"  ],
  ["Carola","Callophyllis variegata"  ],
  ["Dabberlocks (Badderlocks)","Alaria esculenta"  ],
  ["Dulse (Dillisk)","Palmaria palmata"  ],
  ["Eelgrass","Zostera"  ],
  ["Hijiki","Hizikia fusiformis"  ],
  ["Kombu","Laminaria japonica"  ],
  ["Red laver","Porphyra"  ],
  ["Mozuku","Cladosiphon okamuranus"  ],
  ["Nori","Porphyra, Pyropia"  ],
  ["Ogonori","Gracilaria"  ],
  ["Sea grape","Caulerpa lentillifera, Caulerpa racemosa"  ],
  ["Sea lettuce","Ulva lactuca"  ],
  ["Wakame","Undaria pinnatifida"  ],
  ["Sunset Hibiscus","Abelmoschus manihot"  ],
  ["China Jute","Abutilon theophrasti"  ],
  ["Climbing wattle","Acacia pennata"  ],
  ["Dootsi, Ghehi","Agasyllis latifolia"  ],
  ["Common Marshmallow","Althaea officinalis"  ],
  ["Purple amaranth","Amaranthus cruentus"  ],
  ["Common amaranth","Amaranthus retroflexus"  ],
  ["Prickly amaranth","Amaranthus spinosus"  ],
  ["Amaranth","Amaranthus tricolor"  ],
  ["Slender amaranth","Amaranthus viridis"  ],
  ["Garden orache","Atriplex hortensis"  ],
  ["Bank cress","Barbarea verna"  ],
  ["Chik-nam, Kra don","Barringtonia acutangula"  ],
  ["Indian spinach","Basella alba"  ],
  ["Chard","Beta cicla"  ],
  ["Beet, Beetroot","Beta vulgaris"  ],
  ["Common Borage","Borago officinalis"  ],
  ["Abyssinian Cabbage","Brassica carinata"  ],
  ["Indian mustard","Brassica juncea"  ],
  ["Rutabaga","Brassica napus"  ],
  ["Rape Kale","Brassica napus var. pabularia"  ],
  ["Black Mustard","Brassica nigra"  ],
  ["Wild Cabbage","Brassica oleracea"  ],
  ["Kale","Brassica oleracea var. acephala"  ],
  ["Kai-lan","Brassica oleracea var. alboglabra"  ],
  ["Cauliflower","Brassica oleracea var. botrytis"  ],
  ["Cabbage","Brassica oleracea var. capitata"  ],
  ["Brussels Sprouts","Brassica oleracea var. gemmifera"  ],
  ["Broccoli","Brassica oleracea var. italica"  ],
  ["Lacinato kale","Brassica oleracea var. palmifolia"  ],
  ["Turnip","Brassica rapa subsp. rapa"  ],
  ["Bok Choi","Brassica rapa subsp. chinensis"  ],
  ["Chinese Savoy","Brassica oleracea var. sabauda L."  ],
  ["Mizuna","Brassica rapa subsp. nipposinica"  ],
  ["Napa Cabbage","Brassica rapa subsp. pekinensis"  ],
  ["Rapini","Brassica rapa"  ],
  ["Komatsuna","Brassica rapa var. perviridis"  ],
  ["Tatsoi","Brassica rapa var. rosularis"  ],
  ["Rampion","Campanula rapunculus"  ],
  ["Harebell","Campanula versicolor"  ],
  ["Labuyo chili","Capsicum frutescens"  ],
  ["Papaya","Carica papaya"  ],
  ["Wild Coxcomb","Celosia argentea var. argentea"  ],
  ["Asian pennywort, Gotukola","Centella asiatica"  ],
  ["American Wormseed","Chenopodium album"  ],
  ["Southern Huauzontle","Chenopodium ambrosioides"  ],
  ["Good King Henry","Chenopodium berlandieri subsp. nuttalliae"  ],
  ["Tree Spinach","Chenopodium bonus-henricus"  ],
  ["Oak-Leaved Goosefoot","Chenopodium giganteum"  ],
  ["Huauzontle","Chenopodium glaucum"  ],
  ["Quinoa","Chenopodium nuttalliae"  ],
  ["Red Goosefoot","Chenopodium quinoa subsp. quinoa"  ],
  ["Garland chrysanthemum","Chenopodium rubrum"  ],
  ["Endive","Chrysanthemum coronarium"  ],
  ["Curly endive","Cichorium endivia"  ],
  ["Broad-leaved endive","Cichorium endivia var. crispum"  ],
  ["Chicory","Cichorium endivia var. latifolium"  ],
  ["Belgian endive","Cichorium intybus"  ],
  ["Puntarelle","Cichorium intybus var. foliosum"  ],
  ["Radicchio","Cichorium intybus var. foliosum"  ],
  ["Sugarloaf",""  ],
  ["Cabbage thistle","Cichorium intybus"  ],
  ["Miner's lettuce","Cirsium oleraceum"  ],
  ["Siberian spring beauty","Claytonia perfoliata"  ],
  ["African cabbage","Claytonia sibirica"  ],
  ["Ivy Gourd","Cnidoscolus aconitifolius"  ],
  ["Taro","Coccinia grandis"  ],
  ["Jew's mallow","Colocasia esculenta"  ],
  ["Cilantro, Coriander","Corchorus olitorius"  ],
  ["Sea kale","Cosmos caudatus"  ],
  ["Redflower ragleaf","Crambe maritima"  ],
  ["Samphire","Cratoxylum formosum"  ],
  ["Mitsuba","Crotalaria longirostrata"  ],
  ["Caigua","Cucumis prophetarum"  ],
  ["Cardoon","Cyclanthera pedata"  ],
  ["Vegetable fern","Cynara cardunculus"  ],
  ["Perennial Wall-rocket","Diplazium esculentum"  ],
  ["Thong lang","Diplotaxis tenuifolia"  ],
  ["Arugula, Rocket","Erythrina fusca"  ],
  ["Lesser jack","Eruca sativa"  ],
  ["Bhandhanya, Culantro","Emex spinosa"  ],
  ["Fennel","Eryngium foetidum"  ],
  ["Scarlina","Foeniculum vulgare"  ],
  ["Gallant Soldier","Galactites tomentosa"  ],
  ["Ground Ivy","Galinsoga parviflora"  ],
  ["Lotus sweet juice","Glechoma hederacea"  ],
  ["Melinjo","Glinus lotoides"  ],
  ["Okinawan spinach","Gnetum gnemon"  ],
  ["Sea purslane","Gynura crepidioides"  ],
  ["Roselle","Halimione portulacoides"  ],
  ["Shortpod mustard","Hibiscus sabdariffa"  ],
  ["Sea sandwort","Hirschfeldia incana"  ],
  ["Fishwort","Honckenya peploides"  ],
  ["John's Cabbage","Houttuynia cordata"  ],
  ["Shawnee Salad","Hydrophyllum canadense"  ],
  ["Spotted Cat's-ear","Hyoseris radiata"  ],
  ["Catsear","Hypochaeris maculata"  ],
  ["Golden samphire","Hypochaeris radicata"  ],
  ["Elecampane","Inula crithmoides"  ],
  ["Water Spinach","Inula helenium"  ],
  ["Sweet Potato",""  ],
  ["Lablab","Kleinhovia hospita"  ],
  ["Indian Lettuce","Lablab purpureus"  ],
  ["Lettuce","Lactuca perennis"  ],
  ["Celtuce","Lactuca sativa"  ],
  ["Prickly Lettuce","Lactuca sativa"  ],
  ["Bottle Gourd","Lactuca serriola"  ],
  ["Dragon's head","Lagenaria siceraria"  ],
  ["White deadnettle","Lallemantia iberica"  ],
  ["Henbit deadnettle","Lamium album"  ],
  ["Red deadnettle","Lamium amplexicaule"  ],
  ["Nipplewort","Lamium purpureum"  ],
  ["Bush Banana","Launaea sarmentosa"  ],
  ["Hawkbit","Leichhardtia australis"  ],
  ["Field pepperweed","Leontodon tuberosus"  ],
  ["Dittander","Lepidium campestre"  ],
  ["Maca","Lepidium latifolium"  ],
  ["Garden cress","Lepidium meyenii"  ],
  ["Virginia pepperweed","Lepidium sativum"  ],
  ["Phak kratin","Lepidium virginicum"  ],
  ["Lovage","Leucaena leucocephala"  ],
  ["Genjer","Levisticum officinale"  ],
  ["Rice paddy herb","Limnocharis flava"  ],
  ["Gooseneck Loosestrife","Limnophila indica"  ],
  ["Cheeseweed","Malva neglecta"  ],
  ["Mallow","Malva parviflora"  ],
  ["Musk Mallow","Malva sylvestris"  ],
  ["Cassava","Malva verticillata var. crispa"  ],
  ["Semanggi","Manihot esculenta subsp. esculenta"  ],
  ["Kogomi, fiddleheads","Marsilea crenata"  ],
  ["Japanese mint","Megacarpaea polyandra"  ],
  ["Habek mint","Mentha arvensis piperascens"  ],
  ["Sea bluebell","Mentha longifolia"  ],
  ["Ice plant","Mertensia maritima"  ],
  ["Seep monkey flower","Mesembryanthemum crystallinum"  ],
  ["Mauka","Mimulus guttatus"  ],
  ["Noni tree","Mirabilis expansa"  ],
  ["Drumstick tree","Morinda citrifolia"  ],
  ["South-west African moringa","Moringa oleifera"  ],
  ["Ethiopian moringa","Moringa ovalifolia"  ],
  ["Wall lettuce","Moringa stenopetala"  ],
  ["Ujuju","Mycelis muralis"  ],
  ["Parrot feather","Myrianthus arboreus"  ],
  ["Cicely","Myriophyllum brasiliense"  ],
  ["Watercress","Myrrhis odorata"  ],
  ["Phak chet","Nasturtium officinale"  ],
  ["Fragrant Water Lily","Neptunia oleracea Loureiro"  ],
  ["Water Snowflake","Nymphaea odorata"  ],
  ["Yellow floating heart","Nymphoides indica"  ],
  ["Sweet Basil","Nymphoides peltata"  ],
  ["Thai basil","Ocimum basilicum"  ],
  ["Lemon basil","O. basilicum var. thyrsiflora"  ],
  ["Water Celery","Ocimum Ãƒâ€” citriodorum"  ],
  ["Common evening primrose","Oenanthe javanica"  ],
  ["Hooker's Evening-primrose","Oenothera biennis"  ],
  ["Sensitive fern","Oenothera hookeri"  ],
  ["Pheka","Onoclea sensibilis"  ],
  ["Rice","Oroxylum indicum"  ],
  ["Cinnamon fern","Osmorhiza aristata"  ],
  ["Interrupted fern","Osmunda cinnamomea"  ],
  ["Common wood sorrel","Osmunda claytoniana"  ],
  ["Creeping woodsorrel","Oxalis acetosella"  ],
  ["Iron Cross","Oxalis corniculata"  ],
  ["Redwood sorrel","Oxalis deppei"  ],
  ["Common yellow woodsorrel","Oxalis oregana"  ],
  ["Oca","Oxalis stricta"  ],
  ["Mountain sorrel","Oxalis violacea"  ],
  ["Money tree","Oxyria digyna"  ],
  ["Petai","Parkia biglandulosa"  ],
  ["Blue Palo Verde","Parkia speciosa"  ],
  ["Parsnip","Parkinsonia florida"  ],
  ["Golden lace","Pastinaca sativa subsp. sativa"  ],
  ["Empress tree","Patrinia villosa"  ],
  ["Burra Gookeroo","Paulownia tomentosa"  ],
  ["Clearweed","Pedalium murex"  ],
  ["Barbados Gooseberry","Peperomia pellucida"  ],
  ["Perilla","Pergularia daemia"  ],
  ["Water pepper","Perilla frutescens"  ],
  ["Arctic butterbur","Persicaria vulgaris"  ],
  ["Parsley","Petasites frigidus"  ],
  ["Runner Bean","Peucedanum ostruthium"  ],
  ["Lima Bean","Phaseolus coccineus"  ],
  ["Bean","Phaseolus lunatus"  ],
  ["Common Reed","Phaseolus vulgaris"  ],
  ["Rough fogfruit","Phragmites australis"  ],
  ["Star Gooseberry","Phyla scaberrima"  ],
  ["Myrobalan","Phyllanthus acidus"  ],
  ["Round-headed rampion","Phyllanthus emblica"  ],
  ["Indian Pokeberry","Phyteuma orbiculare"  ],
  ["American Pokeweed","Phytolacca acinosa var. esculenta"  ],
  ["Bella Sombra","Phytolacca americana"  ],
  ["Deer calalu","Phytolacca dioica"  ],
  ["Pohpohan","Phytolacca rivinoides"  ],
  ["Aniseed","Pilea melastomoides"  ],
  ["Burnet Saxifrage","Pimpinella anisum"  ],
  ["Japanese Red Pine","Pimpinella saxifraga"  ],
  ["Mexican pepperleaf","Pinus densiflora"  ],
  ["West African pepper","Piper auritum"  ],
  ["Cha-phlu","Piper guineense"  ],
  ["Queensland grass-cloth plant","Piper sarmentosum"  ],
  ["Tree lettuce","Pipturus argenteus"  ],
  ["Chinese Pistache","Pisonia grandis"  ],
  ["Terebinth","Pistacia chinensis"  ],
  ["Water Lettuce","Pistacia terebinthus"  ],
  ["Garden pea","Pistia stratiotes"  ],
  ["Buckshorn plantain","Pisum sativum"  ],
  ["Long-leaved plantain","Plantago coronopus"  ],
  ["Broad-leaved Plantain","Plantago lanceolata"  ],
  ["Himalayan mayapple","Pluchea indica"  ],
  ["Knotweed","Poliomintha incana"  ],
  ["Bistort","Polygonum aviculare"  ],
  ["American Bistort","Polygonum bistorta"  ],
  ["Alpine bistort","Polygonum punctatum"  ],
  ["Trifoliate orange","Polyscias fruticosa"  ],
  ["Common purslane","Pontederia cordata"  ],
  ["Elephant Bush","Portulaca pilosa"  ],
  ["Cowslip","Portulacaria afra"  ],
  ["Primrose","Primula veris"  ],
  ["Kerguelen cabbage","Primula vulgaris"  ],
  ["Prairie turnip","Prunella vulgaris"  ],
  ["Lungwort","Pulicaria odora"  ],
  ["Birch-Leaved Pear","Puya chilensis"  ],
  ["Lesser celandine","Pyrus betulaefolia"  ],
  ["Wild radish","Ranunculus ficaria"  ],
  ["Radish","Raphanus raphanistrum ssp. maritimus"  ],
  ["Chinese radish","Raphanus sativus"  ],
  ["Raffia palm","Raphanus sativus var. longipinnatus"  ],
  ["French Scorzonera","Raphia hookeri"  ],
  ["Meadow beauty","Rheum tataricum"  ],
  ["Roseroot","Rhexia virginica"  ],
  ["Nikau","Rhododendron arboreum"  ],
  ["Blackcurrant","Ribes divaricatum"  ],
  ["Seven Sisters Rose","Rorippa islandica"  ],
  ["Sorrel","Rubus rosaefolius"  ],
  ["Glasswort","Rumex acetosa"  ],
  ["Weeping Willow","Salicornia europaea"  ],
  ["Rosegold pussy willow","Salix daphnoides"  ],
  ["Saltwort","Salix gracilistyla"  ],
  ["Land Seaweed","Salsola kali"  ],
  ["Opposite leaved saltwort","Salsola komarovii"  ],
  ["Toothbrush tree","Salsola soda"  ],
  ["Salad Burnet","Sanguisorba canadensis"  ],
  ["Great Burnet","Sanguisorba minor"  ],
  ["Sassafras","Sanguisorba officinalis"  ],
  ["Katuk","Sassafras albidum"  ],
  ["Eastern Swamp Saxifrage","Sauropus androgynus"  ],
  ["Creeping Rockfoil","Saxifraga pensylvanica"  ],
  ["Tagarnina","Schleichera oleosa"  ],
  ["Spotted golden thistle","Scolymus hispanicus"  ],
  ["Scorzonera","Scolymus maculatus"  ],
  ["Baikal Skullcap","Scorzonera hispanica"  ],
  ["Chayote","Scutellaria baicalensis"  ],
  ["Love-restorer","Sechium edule"  ],
  ["Spreading stonecrop","Sedum anacampseros"  ],
  ["Jenny's stonecrop","Sedum divergens"  ],
  ["Rose crown","Sedum reflexum"  ],
  ["Livelong","Sedum rhodanthum"  ],
  ["Digutiyara","Sedum telephium"  ],
  ["Cassod Tree","Senna occidentalis"  ],
  ["Sesame","Sesamum alatum"  ],
  ["Benniseed","Sesamum indicum"  ],
  ["West Indian pea","Sesamum radiatum"  ],
  ["Sesban","Sesbania grandiflora"  ],
  ["Sea Purselane","Sesbania sesban"  ],
  ["Palm-grass","Sesuvium portulacastrum"  ],
  ["Arrowleaf sida","Sicyos angulatus"  ],
  ["Pepper saxifrage","Sidalcea neomexicana"  ],
  ["Moss campion","Silaum silaus"  ],
  ["Bladder Campion","Silene acaulis"  ],
  ["Blessed milk thistle","Silene vulgaris"  ],
  ["White Mustard","Silybum marianum"  ],
  ["Charlock","Sinapis alba"  ],
  ["London rocket","Sisymbrium crassifolium"  ],
  ["Hedge mustard","Sisymbrium irio"  ],
  ["Alexanders","Sium cicutaefolium"  ],
  ["Chinese potato","Smyrnium olusatrum"  ],
  ["Field sow-thistle","Solidago missouriensis"  ],
  ["Spiny-leaved sow thistle","Sonchus arvensis"  ],
  ["Sow Thistle","Sonchus asper"  ],
  ["Pagoda-tree","Sonchus oleraceus"  ],
  ["Toothache Plant","Sphenostylis stenocarpa"  ],
  ["Spinach","Spilanthes acmella"  ],
  ["Greater Duck-weed","Spinacia oleracea"  ],
  ["Common Chickweed","Stanleya pinnatifida"  ],
  ["Natal orange","Sterculia tragacantha"  ],
  ["Sea Blite","Strychnos spinosa"  ],
  ["Comfrey","Suaeda maritima"  ],
  ["Russian Comfrey","Symphytum officinale"  ],
  ["Malay apple","Synedrella nodiflora"  ],
  ["Jewels of Opar","Syzygium polycephalum"  ],
  ["Tansy","Talinum triangulare"  ],
  ["Dandelion","Taraxacum albidum"  ],
  ["Fluted gourd","Taraxacum officinale"  ],
  ["New Zealand Spinach","Tetragonia implexicoma"  ],
  ["Pennycress","Tetragonia tetragonioides"  ],
  ["Common Thyme","Thlaspi arvense"  ],
  ["Western salsify","Tordylium apulum"  ],
  ["Salsify","Tragopogon dubius"  ],
  ["Goat's Beard","Tragopogon porrifolius"  ],
  ["Alsike Clover","Trichodesma zeylanicum"  ],
  ["Red Clover","Trifolium hybridum"  ],
  ["White Clover","Trifolium pratense"  ],
  ["Sweet Trefoil","Trifolium repens"  ],
  ["Wake-robin","Trigonella corniculata"  ],
  ["White trillium","Trillium erectum"  ],
  ["Painted trillium","Trillium sessile"  ],
  ["Garden Nasturtium","Trillium undulatum"  ],
  ["Dwarf Nasturtium","Tropaeolum majus"  ],
  ["Mashua","Tropaeolum minus"  ],
  ["Coltsfoot","Tulbaghia alliacea"  ],
  ["Ulluco","Typha elephantina"  ],
  ["Siberian elm","Ullucus tuberosus"  ],
  ["Rose Mallow","Ulmus pumila"  ],
  ["Stinging Nettle","Urena lobata"  ],
  ["Annual Nettle","Urtica dioica"  ],
  ["Italian Corn Salad","Urtica urens"  ],
  ["Corn Salad","Valerianella eriocarpa"  ],
  ["European Verbena","Vallaris heynei"  ],
  ["Bitter leaf","Verbena officinalis"  ],
  ["Water Speedwell","Vernonia amygdalina"  ],
  ["Brooklime","Veronica anagallis-aquatica"  ],
  ["Canada Violet","Viola adunca"  ],
  ["Sweet Violet","Viola canadensis"  ],
  ["Bird's Foot Violet","Viola papilionacea"  ],
  ["Common blue violet","Viola pedata"  ],
  ["Amur grape","Vitex doniana"  ],
  ["California wild grape","Vitis amurensis"  ],
  ["Northern Fox Grape","Vitis coignetiae"  ],
  ["Grape","Vitis shuttleworthii"  ],
  ["Wasabi","Vitis vinifera"  ],
  ["Japanese wisteria","Wasabia japonica"  ],
  ["Sea daisy","Wolffia arrhiza"  ],
  ["Yellowhorn","Wollastonia biflora"  ],
  ["Awapuhi","Zanthoxylum planispinum"  ]
]
